version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: blog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: vs4tw
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
      MYSQL_DATABASE: blogdb
    ports:
      - "3306:3306"
    networks:
      - blog-network
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  backend:
    image: stefanhafner/quarkus/hftm:1.0.0-SNAPSHOT
    container_name: blog-backend
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://blog-mysql:3306/blogdb
      QUARKUS_DATASOURCE_USERNAME: dbuser
      QUARKUS_DATASOURCE_PASSWORD: dbuser
    ports:
      - "8080:8080"
    networks:
      - blog-network
    depends_on:
      - mysql
    restart: unless-stopped

networks:
  blog-network:
    driver: bridge

volumes:
  mysql-data:
